export const GET_POKEMON_BASIC_REQUEST = 'GET_POKEMON_BASIC_REQUEST';
export const GET_POKEMON_BASIC_SUCCESS = 'GET_POKEMON_BASIC_SUCCESS';
export const GET_POKEMON_BASIC_FAILURE = 'GET_POKEMON_BASIC_FAILURE';

export const GET_POKEMON_ASIDE_REQUEST = 'GET_POKEMON_ASIDE_REQUEST';
export const GET_POKEMON_ASIDE_SUCCESS = 'GET_POKEMON_ASIDE_SUCCESS';
export const GET_POKEMON_ASIDE_FAILURE = 'GET_POKEMON_ASIDE_FAILURE';

export const GET_SPRITES_REQUEST = 'GET_SPRITES_REQUEST';
export const GET_SPRITES_SUCCESS = 'GET_SPRITES_SUCCESS';
export const GET_SPRITES_FAILURE = 'GET_SPRITES_FAILURE';

export const GET_EVOLUTION_CHAIN_REQUEST = 'GET_EVOLUTION_CHAIN_REQUEST';
export const GET_EVOLUTION_CHAIN_SUCCESS = 'GET_EVOLUTION_CHAIN_SUCCESS';
export const GET_EVOLUTION_CHAIN_FAILURE = 'GET_EVOLUTION_CHAIN_FAILURE';

export const GET_DATA_TABLE_REQUEST = 'GET_DATA_TABLE_REQUEST';
export const GET_DATA_TABLE_SUCCESS = 'GET_DATA_TABLE_SUCCESS';
export const GET_DATA_TABLE_FAILURE = 'GET_DATA_TABLE_FAILURE';