export const GET_DATA_TABLE_REQUEST = 'GET_DATA_TABLE_REQUEST';
export const GET_DATA_TABLE_SUCCESS = 'GET_DATA_TABLE_SUCCESS';
export const GET_DATA_TABLE_FAILURE = 'GET_DATA_TABLE_FAILURE';

export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';

