export const GET_POKEMON_REQUEST = 'GET_POKEMON_REQUEST';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';

export const GET_SPRITES_REQUEST = 'GET_SPRITES_REQUEST';
export const GET_SPRITES_SUCCESS = 'GET_SPRITES_SUCCESS';
export const GET_SPRITES_FAILURE = 'GET_SPRITES_FAILURE';